import { User, Product, StockMovement, Category, Supplier, Alert, AuditLog } from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: 'Philip Ojedokun',
    email: 'admin@stocksense.com',
    role: 'admin',
    status: 'active',
    last_login_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Jane Manager',
    email: 'manager@stocksense.com',
    role: 'manager',
    status: 'active',
    last_login_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 3,
    name: 'Bob Staff',
    email: 'staff@stocksense.com',
    role: 'staff',
    status: 'active',
    last_login_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 4,
    name: 'Inactive User',
    email: 'inactive@stocksense.com',
    role: 'staff',
    status: 'inactive',
    last_login_at: null,
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name: 'Raw Materials', description: 'Basic materials for production', color: 'blue', product_count: 12 },
  { id: 2, name: 'Finished Goods', description: 'Ready to sell products', color: 'green', product_count: 45 },
  { id: 3, name: 'Packaging', description: 'Boxes, labels, and tapes', color: 'amber', product_count: 8 },
  { id: 4, name: 'Electronics', description: 'Sensors, boards, and components', color: 'red', product_count: 24 },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: 1,
    name: 'Global Parts Corp',
    contact_person: 'Jane Smith',
    phone: '+123456789',
    email: 'jane@globalparts.com',
    address: '123 Industrial Way, New York, NY',
    notes: 'Primary supplier for hardware.',
  },
  {
    id: 2,
    name: 'MechTech Solutions',
    contact_person: 'Mike Johnson',
    phone: '+987654321',
    email: 'mike@mechtech.com',
    address: '456 Engineering Dr, Chicago, IL',
    notes: 'Specializes in mechanical gears.',
  },
  {
    id: 3,
    name: 'EcoPack Ltd',
    contact_person: 'Sarah Green',
    phone: '+555123456',
    email: 'sarah@ecopack.com',
    address: '789 Green Rd, Portland, OR',
    notes: 'Sustainable packaging solutions.',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    sku: 'SKU-001',
    name: 'Steel Bearing 20mm',
    description: 'High-precision steel bearing for industrial machinery.',
    category_id: 1,
    supplier_id: 1,
    current_stock: 150,
    reorder_point: 50,
    rop: 60,
    eoq: 200,
    adu: 5,
    velocity: 'fast',
    lead_time_days: 10,
    safety_stock: 20,
    cost_per_order: 50,
    holding_cost: 2,
    storage_location: 'A-12-3',
    unit_of_measure: 'units',
    unit_price: 12.50,
    status: 'active',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-03-20T15:30:00Z',
  },
  {
    id: 2,
    sku: 'SKU-002',
    name: 'Aluminum Housing A1',
    description: 'Cast aluminum housing for motor assemblies.',
    category_id: 1,
    supplier_id: 2,
    current_stock: 15,
    reorder_point: 20,
    rop: 25,
    eoq: 100,
    adu: 2,
    velocity: 'moderate',
    lead_time_days: 14,
    safety_stock: 10,
    cost_per_order: 75,
    holding_cost: 5,
    storage_location: 'B-04-1',
    unit_of_measure: 'units',
    unit_price: 45.00,
    status: 'active',
    created_at: '2024-01-20T11:00:00Z',
    updated_at: '2024-03-24T09:15:00Z',
  },
  {
    id: 3,
    sku: 'SKU-003',
    name: 'Logic Board V2.4',
    description: 'Main control board for automated systems.',
    category_id: 4,
    supplier_id: 1,
    current_stock: 0,
    reorder_point: 10,
    rop: 15,
    eoq: 50,
    adu: 1,
    velocity: 'slow',
    lead_time_days: 30,
    safety_stock: 5,
    cost_per_order: 150,
    holding_cost: 15,
    storage_location: 'E-01-2',
    unit_of_measure: 'units',
    unit_price: 120.00,
    status: 'active',
    created_at: '2024-02-05T14:00:00Z',
    updated_at: '2024-03-22T16:45:00Z',
  },
];

export const MOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 1,
    product_id: 1,
    product_name: 'Steel Bearing 20mm',
    type: 'in',
    quantity: 100,
    notes: 'Restock from Global Parts Corp',
    reference_number: 'PO-9921',
    movement_date: '2024-03-20T15:30:00Z',
    performed_by_name: 'Bob Staff',
  },
  {
    id: 2,
    product_id: 2,
    product_name: 'Aluminum Housing A1',
    type: 'out',
    quantity: 5,
    notes: 'Production line assembly',
    reference_number: 'ORD-4412',
    movement_date: '2024-03-24T09:15:00Z',
    performed_by_name: 'Bob Staff',
  },
  {
    id: 3,
    product_id: 3,
    product_name: 'Logic Board V2.4',
    type: 'out',
    quantity: 10,
    notes: 'Customer order #8842',
    reference_number: 'ORD-8842',
    movement_date: '2024-03-22T16:45:00Z',
    performed_by_name: 'Jane Manager',
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 1,
    type: 'low_stock',
    message: 'Aluminum Housing A1 is below safety threshold (15 left, min 20)',
    product_id: 2,
    product_name: 'Aluminum Housing A1',
    severity: 'warning',
    is_acknowledged: false,
    created_at: '2024-03-24T09:15:00Z',
  },
  {
    id: 2,
    type: 'out_of_stock',
    message: 'Logic Board V2.4 is out of stock!',
    product_id: 3,
    product_name: 'Logic Board V2.4',
    severity: 'critical',
    is_acknowledged: false,
    created_at: '2024-03-22T16:45:00Z',
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 1,
    user_name: 'Philip Ojedokun',
    action: 'LOGIN',
    entity_type: 'USER',
    entity_id: 1,
    details: 'User logged in successfully',
    ip_address: '192.168.1.1',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    user_name: 'Jane Manager',
    action: 'UPDATE',
    entity_type: 'PRODUCT',
    entity_id: 2,
    details: 'Updated stock level for Aluminum Housing A1',
    ip_address: '192.168.1.5',
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
];
